### ISSUE TITLE
Titles for charts in tutorial section

### ISSUE THREAD

**Issue by simzer** [vizzuhq/vizzu-lib-doc#10]
Before each tutorial animation, there should be an inserted animate call, which adds the title of that snippet to the chart (300ms). 
Title values are generated into the snippet registering code.

**Comment by simzer** [comment]
Now at least 4 snippets' effect is not shown because they would alter the missing title.

**Comment by andraskangyal** [comment]
I hope this is why a can't skim thrue the tutorial vizzus by menus. Titles don't appear and (but maybe it has diff reason) when I am coming back from "Color palette & fonts" meupoint to an earlier, palettes has changed.

**Comment by veghdev** [comment]
fixed 0.7 site
