### ISSUE TITLE
Mixed Vizzu rendering

### ISSUE THREAD

**Issue by andraskangyal** [vizzuhq/vizzu-lib-doc#11]
If I scroll down and up then sometimes vizzu rendering is mixed. (For example: there is title on the first chart.) Or inherited color palette changing before we would like to show the color changing, etc.

Sometimes (i can't figure out what it depends on?) I click in vain on "replay" does not animate the chart. And In the same time the scroll also doesn't control the animations.

**Comment by veghdev** [comment]
fixed 0.7 site
