### ISSUE TITLE
Faulty animations

### ISSUE THREAD

**Issue by petervidos** [vizzuhq/vizzu-lib-doc#18]
- **[update: fixed - @simzer]** None of the examples within the animation options of the tutorial work as expected.
- In the shorthand chapter the xAxis.title.bakgroundColor option seems to have no effect
- **[update: fixed - @simzer]** Also in the shorthand chapter the use of the previously saved snapshot doesn't seem to work
- In the events chapter once the red Jazz or the logo vanish event is registered, it will stay in effect, unless the user scrolls to the part of the tutorial where that event is unregistered - can look rather strange if you scroll upwards from the end of the chapter.

**Comment by simzer** [comment]
first and third fixed in 0.5.0 doc.
please use 1 issue per problem to help track the fixes.

**Comment by veghdev** [comment]
fixed 0.7 site
