### ISSUE TITLE
Tutorial - Data chapter - Data cube figure contains wrong value

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-lib-doc#21]
Smooth Jazz should be 174 (instead of 74)
https://lib.vizzuhq.com/latest/#chapter-0.1

**Comment by veghdev** [comment]
@simzer Fixed in vizzu-lib [f12169c](https://github.com/vizzuhq/vizzu-lib/commit/f12169c2b27bd75fd3bbf8274ddb84dd257bd8e8)

**Comment by simzer** [comment]
Released
