### ISSUE TITLE
Tutorial - Color palette & fonts chapter - console.log(chart.style) not working

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-lib-doc#22]
https://lib.vizzuhq.com/latest/#chapter-0.12

use `console.log(chart.styles)` instead of `console.log(chart.style)`

@simzer Are you sure the document is incorrect?
In vizzu.js there are:

`get config()` and `setConfig(config)` (not get configs())
`get styles()` and `setStyle(style)` (not setStyles(style))

it seems to be asymmetric

**Comment by veghdev** [comment]
@simzer if we don't want to break backward compatibility, we can use both
get config() / get configs()
get style() / get styles()

**Comment by simzer** [comment]
We could but I would consider this a bug instead and just fix it.

**Comment by simzer** [comment]
fixed in 0.4.8
