### ISSUE TITLE
Tutorial - Shorthands & Store chapter - last 2 example not working

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-lib-doc#23]
`chart.animate({
    style: { 
        // plot: { xAxis: { label: { fontSize: '150%' } } }
        'plot.xAxis.label.fontSize': '150%',
        'title.backgroundColor': '#A0A0A0'  
    }
})`

`chart.animate(snapshot)`

**Comment by simzer** [comment]
fixed in 0.5.0 doc
