### ISSUE TITLE
Menu scrolls to wring position after site revisit

### ISSUE THREAD

**Issue by simzer** [vizzuhq/vizzu-lib-doc#26]
Reproduction:
1. click on the link [library initialization](http://localhost:5502/docs/test/reference/classes/vizzu.Vizzu.html#initializing) in the [Axes, title, tooltip](https://lib.vizzuhq.com/test/#chapter-0.2)' chapter 
2. click on the browser's back button 
3. click on a tutorial chapter in the menu

Problem:
The site scrolls up to the example section

**Comment by veghdev** [comment]
fixed 0.7 site
