### ISSUE TITLE
analytical_operations examples update

### ISSUE THREAD

**Issue by veghdev** [vizzuhq/vizzu-lib-doc#38]
- [x] add thumbnails and figure into Analytical operations index page @veghdev 
- [x] order examples on Analytical operations index page @veghdev 
- [x] remove animated examples description, add Analytical operations description into examples index page @petervidos 

- [x] quicker fadeout, delay before fadeout, slower fadein, delay after fadein (Andris to specify exact timing) @veghdev  
- [x] rename "Add to / exclude from" something more meaningful, eg. Add/remove series? (Andris to specify name which match his filenaming criteria) @andraskangyal @petervidos 
- [x] rename Other to Miscellaneous @veghdev 

- [x] thumbnail timing: delay after fadein=05, delay before fadeout=0.5, fadeout is perfect I think @veghdev @simzer 

- [x] Remove title:Title from all examples @veghdev

**Comment by simzer** [comment]
- quicker fadeout, delay before fadeout, slower fadein, delay after fadein (Andris to specify exact timing)
- rename "Add to / exclude from" something more meaningful, eg. Add/remove series? (Andris to specify name which match his filenaming criteria)
- rename Other to Miscellaneous

**Comment by petervidos** [comment]
Remove title:Title from all examples
