### ISSUE TITLE
Preview videos not loading in Safari browser under Analytical Operations menu

### ISSUE THREAD

**Issue by KleinK0910** [vizzuhq/vizzu-lib-doc#41]
Preview videos are not loading on the Analytical Operations page of https://lib.vizzuhq.com/latest/examples/ in Safari browser. However, in Chrome, everything loads smoothly, and the videos play without any issues.

I checked the console logs in Safari, but I couldn't find any errors or warnings.

<img width="1258" alt="Screenshot 2023-05-09 at 15 56 46" src="https://github.com/vizzuhq/vizzu-lib-doc/assets/89403945/5b848f4f-fc91-45fa-8d95-b5dc94e5ac91">
<img width="1335" alt="Screenshot 2023-05-09 at 15 54 38" src="https://github.com/vizzuhq/vizzu-lib-doc/assets/89403945/95443931-fc36-4ecd-9800-86bfb47cb492">

**Comment by schaumb** [comment]
There are 2 problems: 
- encoding
- autoplay
